name: docker-push

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

  push:
    branches:
      - 'main'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  docker:
    runs-on: ubuntu-latest

        uses: docker/build-push-action@v3
        with:
          push: true          
          tags: sameh92/reactivities:latest
  deploy:
    needs: docker
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only